name: eslint
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run eslint
        run: make lint
      
       
